# Copyright (c) 2023 okibcn
# This is free software, licensed under the GNU General Public License v3.0
# See /LICENSE for more information.
# https://github.com/okibcn/ScoopMaster
# Description: Scoop Meta-Bucket

name: Scavenger
on:
  schedule:
    - cron: '52 * * * *'
  # runs at minute 52 of each hour.
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled true/false (default: false)'
        required: false
        default: 'false'
      release:
        description: 'Type (yes) for release, (no) will generate an artifact (default: no)'
        required: false
        default: 'no'

jobs:
  build:
    runs-on: windows-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - name: "⏬ Checkout repository"
      uses: actions/checkout@v3



    # - name: "🔧 Download manifests from known buckets"
    #   run: |
    #     cd ..
    #     ./ScoopMaster/bin/scavenger.ps1


    - name: "🔍 Discover known buckets from Scoop-Directory website."
      run: |
        cd ..
        $scoopDBURL = "https://rasa.github.io/scoop-directory/by-apps.html"
        $ErrorActionPreference = 'SilentlyContinue'
        $lBuckets = [System.Collections.ArrayList]@()
        $source = iwr $scoopDBURL
        $source.Content -split '\r?\n' | ForEach-Object -Process {
            if ($_ -match '<h2.*(http[^\"]+)"'){
                [void]$lBuckets.Add($matches[1])
            }
        }
        $lBuckets > Bucket_list.txt
        Write-Host "$($lBuckets.count) buckets found."

        

    - name: "⏬ Download known buckets"
      run: |
        cd ..
        $lBuckets=(cat .\Bucket_list.txt)
        ## CREATE INPUT FILE FOR ARIA2C
        $lZips=$lBuckets | %{
            if( -not ($_ -match 'https:\/\/github.com\/(.+)')){
                $_ >> badrepos.txt
                return}
            $owner_repo=$matches[1].replace('/','~')
            return "$_/archive/refs/heads/master.zip`n    out=$owner_repo.zip"
        }
        $lZips > download_list.txt   

        # DOWNLOAD BUCKETS
        aria2c --save-session aria2-out.txt -j 16 -i download_list.txt -d zips
        (cmd.exe /c dir /s /b /a-d zips) > Zip_list.txt


    - name: "📃 Extract manifests from downloaded buckets"
      run: |
        cd ..
        # EXTRACT MANIFESTS
        7z e -y zips/*.zip  -ojsons/* */bucket/*.json */*.json
        # PREPARE OUTPUT
        Remove-Item -Force -Recurse jsons/*/.*.json
        $nJsons = (cmd.exe /c dir /s /b /a-d jsons).count
        $nZips = (cat .\Zip_list.txt).count
        Write-Host "PROCESS COMPLETED. $nJsons manifests extracted from $nZips downloaded buckets."


    - name: "🧹 Remove old duplicated manifests"
      run: |
        cd ..
        mkdir local -Force | Out-Null
        $progress=0
        $oldpercent=0
        $nlocal=0
        $hVersion = @{}
        $hDate = @{}
        $hBucket = @{}
        $njsons=(cmd.exe /c dir /s /b /a-d jsons).count
        Write-Host "Processing $njsons manifests...`n"
        gci jsons/*/*.json | ForEach-Object{
            # FOR EACH PACKETFILE IN BUCKET
            $name=$_.BaseName
            $date=$_.LastWriteTimeUtc
            if  (-NOT $hDate.ContainsKey($name)){
                # Package not in local repo.
                Move-Item $_ ./local -Force
                $hDate.add($name,$date)
                $hBucket.add($name,$bucket)
                $nlocal++
            }elseif (($date -gt $hDate[$name])){
                # Newer manifest
                Move-Item $_ ./local -Force
                $hDate.Set_Item($name,$date)
                $hBucket.Set_Item($name,$bucket)
            }else {
                # older version or same version but older manifest
            }
            $progress++
            $percent = [math]::round(100 * $progress / $njsons)
            if ($percent -ne $oldpercent){
                Write-Output "$progress/$njsons  ( $percent% )"
                $oldpercent=$percent
            }
            # Write-Progress -Activity "Processing " -Status "$percent% (Selected: $nlocal) processing: $name" -PercentComplete $percent
        }
        Remove-Item jsons -Force -Recurse
        Write-Host "PROCESS COMPLETED. $nlocal different packages with the most recent manifest out of a total of $nJsons manifests."
        if(Test-Path ERROR_manifest.txt){
            Write-Host "The following manifests have errors:"
            cat ./ERROR_manifest.txt
        } 
      

    - name: "📦 Create Package"
      run: |
        ############################
        ##                          ##
        ##      CREATE PACKAGE      ##
        ##                          ##
        ############################

        remove-item bucket -Recurse -Force
        move-item ../local bucket
        move-item ../*.txt .
        echo "UPDATE=$(date -R -u)" >>$GITHUB_ENV

    
    - name: "⭐ Update repo"
      run: |
        git -C . init
        git -C . add -A
        git -C . config --local user.name "GitHub Actions"
        git -C . config --local user.email actions@github.com
        git -C . commit --no-verify -m "Updated on $(date -R -u)"
        $sha=(git -C . rev-parse HEAD)
        git push



    - name: "🐞 Debug session"
      uses: mxschmitt/action-tmate@v3
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'true'
        ## More info at https://til.simonwillison.net/github-actions/debug-tmate
        ##           or https://github.com/mxschmitt/action-tmate


    - name: "👋 If no new sources are available, then we stop."
      if:  env.CANCEL == 'true'
      uses: andymckay/cancel-action@0.3


    - name: "👍 Upload Artifact"
      uses: actions/upload-artifact@v3
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.release != 'yes'
      with:
        name: Logs
        path: |
          *.txt

    - name: "🎉 Publish a new release"
      uses: softprops/action-gh-release@v0.1.15
      # go to https://github.com/OWNER/REPO/settings/actions and
      # in "**"Workflow Permissions" section give actions **Read and Write permissions**.
      if: github.event_name != 'workflow_dispatch' || github.event.inputs.release == 'yes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        files: ../*.txt
#         body: |
#           ${{ env.BODY }}
   
